title: "ILS DOCTORAL SEMINAR PRESENTATION 2024"
author: "Edwin Isidory"
description: "Institute of Aircraft Systems"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_social: true        # show site description and social links in the footer
show_frame: true           # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "topics.html", title: "Topics"}
  - {file: "schedule.pdf", title: "Schedule"}
  - {title: "Awards", file: "awards.md"}
  - {title: "Social Events", file: "events.md"}

  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:bjoern.annighoefer@ils.uni-stuttgart.de"}
  - {title: Github, icon: github, url: "https://github.com/https://github.com/ils.doctoral.seminar.2024"}
  - {title: ILS website, icon: rss, url: "https://www.ils.uni-stuttgart.de/en/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
